import React from "react";

const Button = () => {
  return (
    <>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    <button>Button Component</button>
    </>
  )
}



export default Button;