import React from "react";

const Button = () => {
  return (
    <div style={{ marginTop: 10 }}>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
      <button>Button Component</button>
    </div>
  )
}


export default Button;